name: Release

concurrency:
  group: "release"
  cancel-in-progress: true

on:
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v6
        with:
          node-version: 19
      - name: Export current version
        run: echo "BR1EFLY_VERSION=v$(jq -r .version package.json)" > $GITHUB_ENV
      - run: npm ci
      - run: npm run build
      - run: >-
          cd dist && \
            zip -r ../br1efly.zip ./*
      # TODO: replace with maintained actions
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.BR1EFLY_VERSION }}
          release_name: Release ${{ env.BR1EFLY_VERSION }}
          draft: false
          prerelease: false
      - name: Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: br1efly.zip
          asset_name: br1efly-${{ env.BR1EFLY_VERSION }}.zip
          asset_content_type: application/zip
